_wandb:
    value:
        cli_version: 0.25.1
        e:
            21eel551n7ikk89ux82fm83wpfc55hik:
                args:
                    - --use_wandb
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 96
                cpu_count_logical: 192
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "9374931091456"
                        used: "5963156037632"
                email: ruben.navasardyan@mail.utoronto.ca
                executable: /usr/bin/python3
                git:
                    commit: 65da283a1656793f7fb691c49f94f841887691e3
                    remote: https://github.com/rubentium/PhyloLM.git
                gpu: NVIDIA H100 80GB HBM3
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-47444fc7-ea8c-cef6-aac8-ef408dc8047b
                host: h100-train-0-0
                memory:
                    total: "1623005847552"
                os: Linux-6.8.0-59-generic-x86_64-with-glibc2.35
                program: /mloscratch/homes/navasard/protein_stuff/PhyloLM/train.py
                python: CPython 3.10.12
                root: /mloscratch/homes/navasard/protein_stuff/PhyloLM
                startedAt: "2026-03-29T21:01:35.468212Z"
                writerId: 21eel551n7ikk89ux82fm83wpfc55hik
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 11
                - 49
            "2":
                - 1
                - 11
                - 49
            "3":
                - 16
                - 61
            "4": 3.10.12
            "5": 0.25.1
            "6": 5.4.0
            "12": 0.25.1
            "13": linux-x86_64
batch_size:
    value: 2
checkpoint_dir:
    value: checkpoints
dropout:
    value: 0.1
epochs:
    value: 3
grad_accum_steps:
    value: 12
h_dim:
    value: 128
log_every:
    value: 200
lr:
    value: 0.0005
max_steps:
    value: 5000
memmap_dir:
    value: /mloscratch/homes/navasard/protein_stuff/PhyloLM/../LG_GC_memmaps
num_blocks:
    value: 10
num_heads:
    value: 8
num_workers:
    value: 1
optimizer:
    value: adamw
prefetch:
    value: 2
resume:
    value: null
save_every:
    value: 2500
seed:
    value: 42
use_wandb:
    value: true
wandb_project:
    value: PhyloLM
wandb_run_name:
    value: null
warmup_steps:
    value: 500
weight_decay:
    value: 0.1
